name: TP-GWAS
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - default
  - bioconda
  - conda-forge
dependencies:
  - jupyterlab>3
  - pandas
  - nbresuse
  - python>=3.7
  - pip
  - nodejs
  - r-base=4
  - rpy2
  - simplegeneric # for some reasons needed by rpy2
  - plink=1.90b6.12
  - king=2.2.4
  - r-qqman==0.1.4
  - numpy
  - matplotlib
  - psutil
