name: TP-GWAS-short
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - default
  - bioconda
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - numpy
  - pandas
  - matplotlib
  - jupyterlab>=3.2,<4
  - ipywidgets>=7.6,<8
  - jupyter-resource-usage
  - jupyterlab-topbar
  - jupyterlab-topbar-text
  - jupyterlab-system-monitor
  - nodejs
  - nbresuse
  - python>=3.7
  - nodejs
  - r-base=4
  - rpy2
  - simplegeneric # for some reasons needed by rpy2
  - plink=1.90b6.12
  - king=2.2.4
  - r-qqman==0.1.4
  - psutil
  
